version: '2'

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/crypto_wallet'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:
